INFO 2023-06-29 11:43:33,683 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 11:56:28,815 autoreload Watching for file changes with StatReloader
WARNING 2023-06-29 11:56:44,316 log Not Found: /favicon.ico
INFO 2023-06-29 12:06:12,753 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:06:12,977 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:06:29,652 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/serializers.py changed, reloading.
INFO 2023-06-29 12:06:29,851 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:06:55,669 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/models.py changed, reloading.
INFO 2023-06-29 12:06:55,821 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:07:17,577 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/models.py changed, reloading.
INFO 2023-06-29 12:07:17,765 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:08:29,806 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/models.py changed, reloading.
INFO 2023-06-29 12:08:30,000 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:11:59,966 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/models.py changed, reloading.
INFO 2023-06-29 12:12:00,201 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:20:06,967 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:20:07,144 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:20:29,781 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:20:29,941 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:20:31,071 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:20:31,237 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:22:54,210 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:22:54,374 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:23:22,269 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:23:22,442 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:23:42,213 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:23:42,373 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 12:23:43,550 autoreload /Users/ryanchampin/Development/importlio/api/importlio/proxy/views.py changed, reloading.
INFO 2023-06-29 12:23:43,690 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 14:18:30,159 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:17:06,125 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:51:01,898 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:54:24,147 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-06-29 16:54:24,315 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:54:25,428 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-06-29 16:54:25,619 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:55:02,826 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 16:55:03,007 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:55:51,436 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 16:55:51,600 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:56:41,988 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/models.py changed, reloading.
INFO 2023-06-29 16:56:42,217 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 16:59:06,906 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 16:59:07,166 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:06:12,075 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:06:12,350 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:06:34,221 autoreload Watching for file changes with StatReloader
WARNING 2023-06-29 17:07:13,269 log Bad Request: /product/
WARNING 2023-06-29 17:07:13,363 log Not Found: /favicon.ico
INFO 2023-06-29 17:08:52,600 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:08:52,847 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:08:54,049 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:08:54,240 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:09:13,847 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:09:14,019 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:12:43,775 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:12:43,972 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:12:45,151 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:12:45,343 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:12:58,740 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:12:58,911 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:24:09,775 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:26:37,758 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/settings.py changed, reloading.
INFO 2023-06-29 17:26:37,929 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:26:48,591 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:30:09,652 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/settings.py changed, reloading.
INFO 2023-06-29 17:30:09,827 autoreload Watching for file changes with StatReloader
WARNING 2023-06-29 17:30:19,138 log Bad Request: /product/
INFO 2023-06-29 17:30:55,088 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:30:55,275 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:33:07,474 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:33:07,652 autoreload Watching for file changes with StatReloader
ERROR 2023-06-29 17:33:10,559 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 17, in create
    cleaned_url = um.clean_url(url)
                  ^^
NameError: name 'um' is not defined
INFO 2023-06-29 17:33:55,005 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:33:55,179 autoreload Watching for file changes with StatReloader
ERROR 2023-06-29 17:33:58,198 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py", line 21, in clean_url
    parsed_url = parsed_url._replace(query=urlunparse(cleaned_params.items()))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/.pyenv/versions/3.11.4/lib/python3.11/urllib/parse.py", line 515, in urlunparse
    _coerce_args(*components))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/.pyenv/versions/3.11.4/lib/python3.11/urllib/parse.py", line 125, in _coerce_args
    str_input = isinstance(args[0], str)
                           ~~~~^^^
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 19, in create
    cleaned_url = um.clean_url(url)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py", line 39, in clean_url
    return jsonify({'error': str(e)})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
INFO 2023-06-29 17:34:35,426 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:34:35,614 autoreload Watching for file changes with StatReloader
ERROR 2023-06-29 17:34:38,701 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 19, in create
    cleaned_url = um.clean_url(url)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py", line 38, in clean_url
    raise e
  File "/Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py", line 21, in clean_url
    parsed_url = parsed_url._replace(query=urlunparse(cleaned_params.items()))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/.pyenv/versions/3.11.4/lib/python3.11/urllib/parse.py", line 515, in urlunparse
    _coerce_args(*components))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/.pyenv/versions/3.11.4/lib/python3.11/urllib/parse.py", line 125, in _coerce_args
    str_input = isinstance(args[0], str)
                           ~~~~^^^
IndexError: tuple index out of range
ERROR 2023-06-29 17:35:10,245 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 19, in create
    cleaned_url = um.clean_url(url)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py", line 38, in clean_url
    raise e
  File "/Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py", line 21, in clean_url
    parsed_url = parsed_url._replace(query=urlunparse(cleaned_params.items()))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/.pyenv/versions/3.11.4/lib/python3.11/urllib/parse.py", line 515, in urlunparse
    _coerce_args(*components))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/.pyenv/versions/3.11.4/lib/python3.11/urllib/parse.py", line 125, in _coerce_args
    str_input = isinstance(args[0], str)
                           ~~~~^^^
IndexError: tuple index out of range
INFO 2023-06-29 17:36:07,788 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:36:07,958 autoreload Watching for file changes with StatReloader
ERROR 2023-06-29 17:36:13,916 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 19, in create
    cleaned_url = um.clean_url(url)
                  ^^^^^^^^^^^^^^^^^
TypeError: UrlManager.clean_url() takes 1 positional argument but 2 were given
INFO 2023-06-29 17:37:45,121 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:37:45,301 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:40:42,407 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:40:42,580 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:40:43,822 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:40:43,975 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:48:27,199 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:48:40,731 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:48:40,920 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:49:22,128 autoreload /Users/ryanchampin/Development/importlio/api/importlio/scraper/url_manager.py changed, reloading.
INFO 2023-06-29 17:49:22,292 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:50:12,895 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:50:13,074 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:56:11,823 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:56:12,009 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:56:17,228 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:56:17,402 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 17:56:32,988 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-06-29 17:56:33,168 autoreload Watching for file changes with StatReloader
INFO 2023-06-29 18:16:55,039 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 01:18:01,562 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 01:26:52,327 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 02:53:43,602 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-07-01 02:53:43,913 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 04:32:19,160 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 04:44:27,746 autoreload Watching for file changes with StatReloader
ERROR 2023-07-01 06:34:14,952 log Internal Server Error: /scraper/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 23, in create
    for url in urls:
TypeError: 'NoneType' object is not iterable
INFO 2023-07-01 06:36:26,137 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:37:30,102 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-07-01 06:37:30,377 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:37:33,543 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-07-01 06:37:33,723 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:38:28,590 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:38:56,424 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-07-01 06:38:56,612 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:40:19,995 autoreload /Users/ryanchampin/Development/importlio/api/importlio/import_product/views.py changed, reloading.
INFO 2023-07-01 06:40:20,265 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:42:47,117 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/settings.py changed, reloading.
INFO 2023-07-01 06:42:47,369 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:42:58,739 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/settings.py changed, reloading.
INFO 2023-07-01 06:42:58,945 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:44:01,498 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 06:44:01,662 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:52:27,226 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 06:52:27,490 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:52:39,947 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 06:52:40,131 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:53:24,529 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-07-01 06:53:24,761 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:54:18,161 autoreload /Users/ryanchampin/Development/importlio/api/importlio/importlio/urls.py changed, reloading.
INFO 2023-07-01 06:54:18,340 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 06:56:03,808 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 07:01:14,771 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:01:15,008 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 07:02:00,502 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:02:00,728 autoreload Watching for file changes with StatReloader
ERROR 2023-07-01 07:35:14,378 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 29, in create
    for url in urls:
TypeError: 'NoneType' object is not iterable
ERROR 2023-07-01 07:36:13,215 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 23, in create
    urls = request.data.get('product_urls')
           ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
ERROR 2023-07-01 07:36:54,991 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 29, in create
    for url in urls:
TypeError: 'NoneType' object is not iterable
INFO 2023-07-01 07:37:28,392 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:37:28,721 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 07:37:30,973 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:37:31,149 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 07:37:32,354 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:37:32,526 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 07:40:43,448 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:40:43,684 autoreload Watching for file changes with StatReloader
INFO 2023-07-01 07:41:08,646 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:41:08,840 autoreload Watching for file changes with StatReloader
WARNING 2023-07-01 07:41:13,196 log Bad Request: /product/
INFO 2023-07-01 07:47:57,522 autoreload /Users/ryanchampin/Development/importlio/api/importlio/product/views.py changed, reloading.
INFO 2023-07-01 07:47:57,817 autoreload Watching for file changes with StatReloader
ERROR 2023-07-01 07:54:06,449 log Internal Server Error: /product/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/api/importlio/product/views.py", line 23, in create
    urls = request.data.get('urls')
           ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
INFO 2023-07-01 08:04:38,407 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 05:01:19,342 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 05:01:40,773 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 05:01:56,888 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 05:02:12,545 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 21:10:00,477 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 21:11:13,150 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 21:11:40,775 autoreload Watching for file changes with StatReloader
INFO 2023-07-02 21:12:46,731 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:14:08,717 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:14:41,785 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:14:42,111 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:17:04,406 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:17:04,645 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:17:05,801 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:17:06,102 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:17:22,674 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:17:22,982 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:17:33,384 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:17:33,632 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:17:40,921 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:17:41,180 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:18:10,048 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:18:10,359 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:18:12,534 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:18:12,765 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:18:13,900 autoreload /Users/ryanchampin/Development/importlio/src/backend/users/models.py changed, reloading.
INFO 2023-07-04 04:18:14,161 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:18:49,027 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-04 04:18:49,338 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:18:50,500 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-04 04:18:50,771 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:48:53,278 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 04:49:22,125 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-04 04:49:22,396 autoreload Watching for file changes with StatReloader
WARNING 2023-07-04 04:49:27,499 log Not Found: /signin/
WARNING 2023-07-04 04:49:27,681 log Not Found: /favicon.ico
INFO 2023-07-04 04:59:53,429 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-04 04:59:53,760 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:01:27,559 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-04 05:01:27,880 autoreload Watching for file changes with StatReloader
WARNING 2023-07-04 05:02:18,584 log Not Found: /signin/
INFO 2023-07-04 05:02:56,738 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-04 05:02:57,086 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:02:58,339 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-04 05:02:58,602 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:03:44,829 autoreload Watching for file changes with StatReloader
WARNING 2023-07-04 05:03:51,348 log Not Found: /admin/login/
WARNING 2023-07-04 05:03:54,628 log Not Found: /signin/
INFO 2023-07-04 05:04:09,771 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-04 05:04:10,111 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:04:15,171 autoreload Watching for file changes with StatReloader
WARNING 2023-07-04 05:04:19,283 log Not Found: /signin/
WARNING 2023-07-04 05:04:28,047 log Not Found: /admin/login/
WARNING 2023-07-04 05:06:58,234 log Not Found: /admin/login/
INFO 2023-07-04 05:07:33,654 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-04 05:07:33,999 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:07:45,396 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-04 05:07:45,633 autoreload Watching for file changes with StatReloader
WARNING 2023-07-04 05:07:49,155 log Not Found: /favicon.ico
WARNING 2023-07-04 05:07:53,665 log Not Found: /favicon.ico
WARNING 2023-07-04 05:07:55,355 log Not Found: /favicon.ico
INFO 2023-07-04 05:13:34,038 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/models.py changed, reloading.
INFO 2023-07-04 05:13:34,386 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:13:38,629 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/models.py changed, reloading.
INFO 2023-07-04 05:13:38,871 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 05:18:13,462 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 06:54:45,283 autoreload Watching for file changes with StatReloader
INFO 2023-07-04 06:56:22,369 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/models.py changed, reloading.
INFO 2023-07-04 06:56:22,674 autoreload Watching for file changes with StatReloader
WARNING 2023-07-04 06:56:37,931 log Not Found: /favicon.ico
DEBUG 2023-07-04 06:57:10,578 resource Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x113ec87c0>.
WARNING 2023-07-04 22:02:45,493 log Not Found: /favicon.ico
INFO 2023-07-04 23:23:11,222 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/serializers.py changed, reloading.
INFO 2023-07-04 23:23:11,694 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 02:38:17,560 log Not Found: /favicon.ico
INFO 2023-07-05 02:54:30,064 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:23:45,721 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:23:46,076 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:24:07,771 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:24:08,031 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:24:09,211 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:24:09,466 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:28:33,486 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:28:33,814 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:28:35,021 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:28:35,285 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:28:40,576 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:28:40,849 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:30:07,168 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 03:30:07,431 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:47:11,459 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:47:11,734 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:47:23,040 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 03:47:23,287 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:55:06,645 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:55:06,985 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:56:32,645 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:56:32,895 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:56:33,976 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:56:34,223 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:57:08,277 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:57:58,894 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:57:59,142 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:57:59,154 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:57:59,405 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:03,265 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:03,517 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:03,526 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:03,779 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:43,253 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:43,475 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:43,512 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:43,733 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:53,975 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:54,227 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:54,798 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:55,053 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:58:55,338 autoreload /Users/ryanchampin/Development/importlio/src/backend/user_profile/views.py changed, reloading.
INFO 2023-07-05 03:58:55,595 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:59:22,575 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 03:59:22,825 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 03:59:23,109 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 03:59:23,370 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:00:04,121 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 04:00:04,388 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:00:04,579 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 04:00:04,850 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:23:55,088 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 04:23:55,602 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 04:26:08,755 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:26:38,354 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 04:26:38,610 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:27:03,075 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 04:27:03,328 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:43:12,734 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 04:43:12,987 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 04:43:14,141 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 04:43:14,304 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:04:10,349 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 05:04:33,978 log Not Found: /favicon.ico
ERROR 2023-07-05 05:04:35,673 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: authentication_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/generic/edit.py", line 152, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/contrib/auth/forms.py", line 242, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 54, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: authentication_user
INFO 2023-07-05 05:08:00,760 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 05:08:00,997 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:11:26,294 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/admin.py changed, reloading.
INFO 2023-07-05 05:11:26,527 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:14:49,997 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 05:14:50,260 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:14:58,603 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/utils.py changed, reloading.
INFO 2023-07-05 05:14:58,804 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:15:01,018 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/admin.py changed, reloading.
INFO 2023-07-05 05:15:01,225 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:15:06,482 autoreload /Users/ryanchampin/Development/importlio/src/backend/social_auth/google.py changed, reloading.
INFO 2023-07-05 05:15:06,689 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:16:56,076 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:17:29,839 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:17:53,370 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:19:01,085 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:19:29,407 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:19:51,492 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:23:46,461 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 05:23:46,721 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:25:46,830 autoreload /Users/ryanchampin/Development/importlio/src/backend/proxy/urls.py changed, reloading.
INFO 2023-07-05 05:25:47,068 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:27:10,411 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:38:24,652 autoreload /Users/ryanchampin/Development/importlio/src/backend/social_auth/google.py changed, reloading.
INFO 2023-07-05 05:38:24,941 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:44:21,645 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 05:44:21,936 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:44:48,707 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 05:44:48,967 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 05:45:16,885 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 05:45:17,118 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 06:07:01,725 log Not Found: /blog
WARNING 2023-07-05 06:07:01,890 log Not Found: /favicon.ico
INFO 2023-07-05 06:12:10,220 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/models.py changed, reloading.
INFO 2023-07-05 06:12:10,501 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 06:12:28,017 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/models.py changed, reloading.
INFO 2023-07-05 06:12:28,234 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 06:23:34,899 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/models.py changed, reloading.
INFO 2023-07-05 06:23:35,210 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 06:25:20,027 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 07:21:26,904 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 07:23:01,743 log Forbidden: /social_auth/google/
INFO 2023-07-05 08:38:04,058 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 08:49:10,420 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 08:49:34,196 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 08:49:34,419 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 08:59:37,653 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:10:53,769 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 10:11:49,399 log Bad Request: /api/auth/register/
WARNING 2023-07-05 10:13:08,341 log Unauthorized: /api/auth/user/
WARNING 2023-07-05 10:13:15,631 log Unauthorized: /api/auth/user/
INFO 2023-07-05 10:13:42,954 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:13:43,150 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:13:53,692 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:13:53,874 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:15:43,007 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/urls.py changed, reloading.
INFO 2023-07-05 10:15:43,190 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:16:23,919 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:16:24,087 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:16:25,293 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:16:25,453 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:22:57,294 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:22:57,476 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:23:33,502 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:23:33,678 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:23:34,874 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/settings.py changed, reloading.
INFO 2023-07-05 10:23:35,038 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:24:04,281 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 10:24:04,447 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:24:05,648 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/views.py changed, reloading.
INFO 2023-07-05 10:24:05,814 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:24:27,733 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/urls.py changed, reloading.
INFO 2023-07-05 10:24:27,902 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 10:24:29,105 autoreload /Users/ryanchampin/Development/importlio/src/backend/authentication/urls.py changed, reloading.
INFO 2023-07-05 10:24:29,265 autoreload Watching for file changes with StatReloader
ERROR 2023-07-05 10:29:13,170 log Internal Server Error: /api/auth/google/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/allauth/socialaccount/providers/google/views.py", line 21, in complete_login
    identity_data = jwt.decode(
                    ^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 254, in _validate_claims
    self._validate_aud(payload, audience)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 336, in _validate_aud
    raise InvalidAudienceError("Audience doesn't match")
jwt.exceptions.InvalidAudienceError: Audience doesn't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/views.py", line 125, in post
    self.serializer.is_valid(raise_exception=True)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/registration/serializers.py", line 157, in validate
    login = self.get_social_login(adapter, app, social_token, response={'id_token': token})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/registration/serializers.py", line 61, in get_social_login
    social_login = adapter.complete_login(request, app, token, response=response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/allauth/socialaccount/providers/google/views.py", line 39, in complete_login
    raise OAuth2Error("Invalid id_token") from e
allauth.socialaccount.providers.oauth2.client.OAuth2Error: Invalid id_token
ERROR 2023-07-05 10:32:00,121 log Internal Server Error: /api/auth/google/
Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/allauth/socialaccount/providers/google/views.py", line 21, in complete_login
    identity_data = jwt.decode(
                    ^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 254, in _validate_claims
    self._validate_aud(payload, audience)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/jwt/api_jwt.py", line 336, in _validate_aud
    raise InvalidAudienceError("Audience doesn't match")
jwt.exceptions.InvalidAudienceError: Audience doesn't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/views.py", line 125, in post
    self.serializer.is_valid(raise_exception=True)
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/registration/serializers.py", line 157, in validate
    login = self.get_social_login(adapter, app, social_token, response={'id_token': token})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/dj_rest_auth/registration/serializers.py", line 61, in get_social_login
    social_login = adapter.complete_login(request, app, token, response=response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanchampin/Development/importlio/src/backend/env/lib/python3.11/site-packages/allauth/socialaccount/providers/google/views.py", line 39, in complete_login
    raise OAuth2Error("Invalid id_token") from e
allauth.socialaccount.providers.oauth2.client.OAuth2Error: Invalid id_token
INFO 2023-07-05 11:09:17,551 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 11:11:04,817 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 11:20:42,622 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 11:20:59,061 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 11:20:59,231 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 11:21:00,339 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 11:21:00,500 autoreload Watching for file changes with StatReloader
INFO 2023-07-05 11:21:05,689 autoreload /Users/ryanchampin/Development/importlio/src/backend/importlio/urls.py changed, reloading.
INFO 2023-07-05 11:21:05,859 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 11:21:21,830 log Not Found: /favicon.ico
WARNING 2023-07-05 11:21:28,423 log Unauthorized: /current/
WARNING 2023-07-05 11:21:42,171 log Unauthorized: /current/
INFO 2023-07-05 11:39:33,006 autoreload Watching for file changes with StatReloader
WARNING 2023-07-05 13:59:51,241 log Unauthorized: /current/
WARNING 2023-07-05 13:59:51,427 log Not Found: /favicon.ico
